spring.application.name=weagle-api

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/weagle

server.port=8080

jwt.secret=
jwt.expiration=86400000

ai.provider=openrouter
ai.api-key=
ai.model=openai/gpt-4o-mini